version: 2
jobs:
  build:
    resource_class: small
    docker:
      - image: firestarteralchemic/circleci-learning-docker:latest
    steps:
      - checkout
      - run:
          command: |
            make
      - store_artifacts:
              path: bin/test
              destination: artifact-test
